FROM python:3.14-slim

WORKDIR /app

COPY docker/entrypoint.backend.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

COPY CycleUni-BE/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]