FROM node:24.15.0-bookworm-slim

WORKDIR /app

COPY docker/entrypoint.cfedgechat.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

COPY CFEdgeChat/package.json CFEdgeChat/package-lock.json ./
RUN npm install

EXPOSE 8787

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]